const $=id=>document.getElementById(id);
const fmt=n=>Number(n).toFixed(1);
const todayISO=()=>new Date().toISOString().slice(0,10);
const DAY=86400000, WEEK=7*DAY;
const defaultState={settings:{name:'Patrice',startWeight:116,goalWeight:78,heightCm:178,startDate:'2026-07-03',injectionDay:5,injectionTime:'22:00'},weights:[{date:'2026-07-03',value:116}],injections:[],symptoms:[]};
let state=load(), selectedSite='Ventre gauche', currentTab='weights', deferredInstall=null;
function load(){try{return {...defaultState,...JSON.parse(localStorage.mission69||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.mission69=JSON.stringify(state);render()}
function weeksSinceStart(){return Math.max(0,Math.floor((new Date(todayISO())-new Date(state.settings.startDate))/WEEK))}
function doseForWeek(w){if(w<4)return .25;if(w<8)return .5;if(w<12)return 1;if(w<16)return 1.7;return 2.4}
function latestWeight(){return [...state.weights].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||{value:state.settings.startWeight,date:state.settings.startDate}}
function bmi(w=latestWeight().value){let h=state.settings.heightCm/100;return w/(h*h)}
function bmiClass(v){return v<25?'Normal':v<30?'Surpoids':v<35?'Obésité classe I':v<40?'Obésité classe II':'Obésité classe III'}
function nextInjectionDate(){let now=new Date();let target=new Date(now);let [hh,mm]=state.settings.injectionTime.split(':').map(Number);target.setHours(hh,mm,0,0);let diff=(state.settings.injectionDay-target.getDay()+7)%7;if(diff===0 && target<now)diff=7;target.setDate(target.getDate()+diff);return target}
function drugLevel(){let halfLife=7, now=new Date();let level=0;for(let inj of state.injections){let days=(now-new Date(inj.date+'T'+(inj.time||state.settings.injectionTime)))/DAY;if(days>=0)level+=(inj.dose||doseForWeek(weeksSinceStart()))*Math.pow(.5,days/halfLife)}let max=2.4/(1-Math.pow(.5,7/7));return Math.min(100,Math.round(level/max*100))}
function projection(){let arr=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));let last=arr.at(-1)||{date:state.settings.startDate,value:state.settings.startWeight};let out=[];let d=new Date(last.date);let w=Number(last.value);for(let i=1;i<=26;i++){let rate=i<5?.9:i<13?.7:.45;w=Math.max(state.settings.goalWeight,w-rate);d=new Date(d.getTime()+WEEK);out.push({date:d.toISOString().slice(0,10),value:+w.toFixed(1),projection:true})}return out}
function render(){let s=state.settings,l=latestWeight(), lost=s.startWeight-l.value, total=s.startWeight-s.goalWeight, left=l.value-s.goalWeight; $('hello').textContent=`Bonjour ${s.name}`;$('currentWeight').textContent=fmt(l.value);$('lostText').textContent=`${fmt(Math.max(0,lost))} kg perdus`;$('leftText').textContent=`${fmt(Math.max(0,left))} kg restants`;$('goalProgress').style.width=`${Math.max(0,Math.min(100,lost/total*100))}%`;let prev=state.weights.length>1?[...state.weights].sort((a,b)=>a.date.localeCompare(b.date)).at(-2).value:l.value;$('trendBadge').textContent=l.value<prev?`▼ ${fmt(prev-l.value)} kg`:l.value>prev?`▲ ${fmt(l.value-prev)} kg`:'Stable';let b=bmi();$('bmi').textContent=fmt(b);$('bmiText').textContent=bmiClass(b);let w=weeksSinceStart();$('nextDose').textContent=doseForWeek(w).toString();$('weekPill').textContent=`Semaine ${w}`;let nd=nextInjectionDate();$('nextDate').textContent=nd.toLocaleDateString('fr-CH',{weekday:'long',day:'2-digit',month:'2-digit'})+' à '+s.injectionTime;$('drugLevel').textContent=drugLevel()+' %';renderSites();renderSymptoms();renderMilestones();renderHistory();drawWeightChart();drawLevelChart()}
function renderSites(){let sites=['Ventre gauche','Ventre droit','Cuisse gauche','Cuisse droite','Bras'];$('siteChooser').innerHTML=sites.map(x=>`<button class="chip ${x===selectedSite?'active':''}" data-site="${x}">${x}</button>`).join('');document.querySelectorAll('[data-site]').forEach(b=>b.onclick=()=>{selectedSite=b.dataset.site;renderSites()})}
function renderSymptoms(){let list=['🙂 Rien','🤢 Nausée','🔥 Reflux','💩 Transit','😴 Fatigue','😵 Vertige','💧 Soif','🍽️ Satiété'];$('symptoms').innerHTML=list.map(x=>`<button class="chip" data-sym="${x}">${x}</button>`).join('');document.querySelectorAll('[data-sym]').forEach(b=>b.onclick=()=>{state.symptoms.unshift({date:todayISO(),value:b.dataset.sym});save()})}
function renderMilestones(){let cw=latestWeight().value;let ms=[110,105,100,95,90,85,80,78];$('milestones').innerHTML=ms.map(m=>`<div class="mile ${cw<=m?'done':''}"><b>${m} kg</b><span>${cw<=m?'Déverrouillé':'reste '+fmt(cw-m)+' kg'}</span></div>`).join('')}
function renderHistory(){let data=currentTab==='weights'?[...state.weights].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>[x.date,fmt(x.value)+' kg']):currentTab==='injections'?[...state.injections].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>[x.date,`${x.dose} mg · ${x.site}`]):[...state.symptoms].slice(0,30).map(x=>[x.date,x.value]);$('history').innerHTML=data.length?data.map(x=>`<div class="historyItem"><span>${x[0]}</span><b>${x[1]}</b></div>`).join(''):'<p class="muted">Aucune donnée.</p>'}
function drawChart(canvas,points,opts={}){let c=$(canvas),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=(opts.h||c.height)*dpr;ctx.scale(dpr,dpr);let w=r.width,h=opts.h||c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=1;for(let i=0;i<4;i++){let y=20+i*(h-40)/3;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(points.length<2)return;let vals=points.map(p=>p.value),min=Math.min(...vals)-2,max=Math.max(...vals)+2;let x=i=>20+i*(w-40)/(points.length-1), y=v=>h-20-(v-min)/(max-min)*(h-40);ctx.strokeStyle='rgba(124,240,196,.95)';ctx.lineWidth=3;ctx.beginPath();points.forEach((p,i)=>{i?ctx.lineTo(x(i),y(p.value)):ctx.moveTo(x(i),y(p.value))});ctx.stroke();ctx.fillStyle='rgba(124,240,196,1)';points.forEach((p,i)=>{if(!p.projection){ctx.beginPath();ctx.arc(x(i),y(p.value),4,0,Math.PI*2);ctx.fill()}});ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='12px -apple-system';ctx.fillText(fmt(max-2)+' kg',22,16);ctx.fillText(fmt(min+2)+' kg',22,h-8)}
function drawWeightChart(){let pts=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));if($('chartMode').value==='projection')pts=pts.concat(projection());drawChart('weightChart',pts,{h:220})}
function drawLevelChart(){let pts=[];let now=new Date();for(let i=29;i>=0;i--){let d=new Date(now-i*DAY),level=0;for(let inj of state.injections){let days=(d-new Date(inj.date+'T'+(inj.time||state.settings.injectionTime)))/DAY;if(days>=0)level+=(inj.dose||.25)*Math.pow(.5,days/7)}pts.push({value:level})}drawChart('levelChart',pts,{h:90})}
$('addWeight').onclick=()=>{let v=Number($('weightInput').value);if(!v||v<40||v>250)return alert('Poids invalide');state.weights.push({date:todayISO(),value:+v.toFixed(1)});$('weightInput').value='';save()};
$('addInjection').onclick=()=>{let w=weeksSinceStart();state.injections.unshift({date:todayISO(),time:state.settings.injectionTime,dose:doseForWeek(w),site:selectedSite});save()};
$('chartMode').onchange=drawWeightChart;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{currentTab=t.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderHistory()});
$('settingsBtn').onclick=()=>{let s=state.settings;['StartWeight','GoalWeight','Height','StartDate','InjectionDay','InjectionTime'].forEach(k=>{let el=$('s'+k),key=k.charAt(0).toLowerCase()+k.slice(1); if(key==='height')key='heightCm'; if(el)el.value=s[key]});$('settingsDialog').showModal()};
$('saveSettings').onclick=()=>{state.settings.startWeight=Number($('sStartWeight').value);state.settings.goalWeight=Number($('sGoalWeight').value);state.settings.heightCm=Number($('sHeight').value);state.settings.startDate=$('sStartDate').value;state.settings.injectionDay=Number($('sInjectionDay').value);state.settings.injectionTime=$('sInjectionTime').value;save()};
$('exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mission69-sauvegarde-'+todayISO()+'.json';a.click()};
$('importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save()}catch{alert('Fichier invalide')}};r.readAsText(f)};
$('resetBtn').onclick=()=>{if(confirm('Effacer toutes les données locales ?')){localStorage.removeItem('mission69');state=structuredClone(defaultState);save()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;$('installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
render();
